name: Get Secret
on:
  push:
    branches: ["main"]

jobs:
  reveal-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Save secret to file
        run: echo -n "${{ secrets.TD_PIZZA }}" > secret.txt

      - name: Upload secret artifact
        uses: actions/upload-artifact@v4
        with:
          name: raw-secret
          path: secret.txt