name: TestDriver.ai

on:
  push:
    branches: ["main", "test-clone-repo"]
  pull_request:
  workflow_dispatch:

permissions:
    contents: read # To allow the action to read repository contents
    pull-requests: write # To allow the action to create/update pull request comments

jobs:
  test:
    name: "TestDriver"
    runs-on: ubuntu-latest
    steps:
      - uses: testdriverai/action@test-clone-repo
        with:
          key: ${{secrets.TESTDRIVER_API_KEY}}
          clone-repo: false
          prerun: |
            node --version
            npm install
            npm run build
            npm install dashcam-chrome --save
            Start-Process "C:/Program Files/Google/Chrome/Application/chrome.exe" -ArgumentList "--start-maximized","--load-extension=$(pwd)/node_modules/dashcam-chrome/build","--allow-file-access-from-files","$(pwd)/dist/index.html"
            Start-Sleep -Seconds 20
          prompt: |
            1. /run testdriver/test.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FORCE_COLOR: "3"
          TD_PIZZA: ${{ secrets.TD_PIZZA}}
